package com.newcore.orbps.service.cmds.api;

import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-02-10T14:18:37.875+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://service.ws.erp.sinosoft.com", name = "UniQueryWebServicePortType")
public interface UniQueryWebServicePortType {

	@WebResult(name = "return", targetNamespace = "http://www.e-chinalife.com/soa/")
	@RequestWrapper(localName = "getQueryResult", targetNamespace = "http://www.e-chinalife.com/soa/", className = "com.newcore.orbps.service.api.GetQueryResult")
	   
	@ResponseWrapper(localName = "getQueryResultResponse", targetNamespace = "http://www.e-chinalife.com/soa/", className = "com.newcore.orbps.service.api.GetQueryResultResponse")
    public String getQueryResult(@WebParam(name = "args0", targetNamespace = "http://www.e-chinalife.com/soa/") String args0);
}
